# fly.toml app configuration file generated for solitary-voice-1579 on 2023-11-03T21:47:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "solitary-voice-1579"
primary_region = "mia"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
